## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [1]:
import pandas as pd

In [2]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
df = pd.read_csv("train - train.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
grouped=df.groupby("Pclass")

In [5]:
list(grouped.groups.keys())

[1, 2, 3]

#### `Avg age`

In [6]:
grouped.agg({
    "Age":"mean"
})

              Age
Pclass
1       38.233441
2       29.877630
3       25.140620

#### `No. of nan values in age in each class of p_class`

In [7]:
def nan_value(grouped):
    for g,data in grouped:
        print(g,":",data.isnull().sum())
nan_value(grouped["Age"])

1 : 30
2 : 11
3 : 136

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [8]:
nan_value(grouped["Embarked"])

1 : 2
2 : 0
3 : 0

In [9]:
print(df["Embarked"])

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [10]:
def repl(group):
    mode = group["Embarked"].mode()[0]
    group["Embarked"] = group["Embarked"].fillna(mode)
    return group

df.groupby("Pclass", group_keys=False).apply(repl)

C:\Users\Nevid\AppData\Local\Temp\ipykernel_7396\2770629100.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("Pclass", group_keys=False).apply(repl)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
nan_value(grouped["Embarked"])

1 : 2
2 : 0
3 : 0

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [12]:
duo_grouped=df.groupby(["Embarked","Pclass"])

In [13]:
list(duo_grouped.groups.keys())

[('C', 1),
 ('C', 2),
 ('C', 3),
 ('Q', 1),
 ('Q', 2),
 ('Q', 3),
 ('S', 1),
 ('S', 2),
 ('S', 3),
 (nan, 1)]

## `AVG Fare`

In [14]:
duo_grouped["Fare"].mean().round(2)

Embarked  Pclass
C         1         104.72
          2          25.36
          3          11.21
Q         1          90.00
          2          12.35
          3          11.18
S         1          70.36
          2          20.33
          3          14.64
Name: Fare, dtype: float64

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [15]:
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")

In [16]:
fifa_df.head(3)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3

In [17]:
grouped_fifa=fifa_df.groupby("Team",group_keys=False)
grouped_fifa.groups.keys()

dict_keys(['Argentina', 'Australia', 'Belgium', 'Brazil', 'Cameroon', 'Canada', 'Costa Rica', 'Croatia', 'Denmark', 'Ecuador', 'England', 'France', 'Germany', 'Ghana', 'Iran', 'Japan', 'Korea Republic', 'Mexico', 'Morocco', 'Netherlands', 'Poland', 'Portugal', 'Qatar', 'Saudi Arabia', 'Senegal', 'Serbia', 'Spain', 'Switzerland', 'Tunisia', 'United States', 'Uruguay', 'Wales'])

In [18]:
def z_normalization(group,columns=[]):
    for column in columns:
        group[column]=(group[column]-group[column].min())/(group[column].max()-group[column].min())
    return group

In [19]:
grouped_fifa.apply(z_normalization,columns=["Passes","Passes Completed"],include_groups=True)

C:\Users\Nevid\AppData\Local\Temp\ipykernel_7396\1172554982.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_fifa.apply(z_normalization,columns=["Passes","Passes Completed"],include_groups=True)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,0.878788,0.829268,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,1.000000,1.000000,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,1.000000,1.000000,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,0.000000,0.000000,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,0.487179,0.514286,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,...,11,3,1.000000,1.000000,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,...,13,2,0.114068,0.164609,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,...,11,2,0.748588,0.740634,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,...,26,4,0.528634,0.425532,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,...,19,4,0.420213,0.306849,24,3,5,28,4,0

In [20]:
# - minimum "Passess"
# - maximum "Passess"
# - minimum "Yellow Cards"
# - maximum "Yellow cards"
# - average "Yellow Cards"
# - maximum "Attempted Line Breaks"
# - minimum "Attempted Line Breaks"
# - standardard deviation of "Attempted Line Breaks"
# - average Possession
grouped_fifa.agg({
    "Passes":["min","max"],
    "Yellow Cards":["min","max","mean"],
    "Attempted Line Breaks":["min","max","std"],
    "Possession (%)":"mean"
}).head()

          Passes      Yellow Cards               Attempted Line Breaks       \
             min  max          min max      mean                   min  max
Team
Argentina    408  862            0   8  2.285714                   141  249
Australia    286  466            0   3  1.750000                   133  171
Belgium      512  685            1   3  1.666667                   167  195
Brazil       548  695            0   3  1.200000                   164  193
Cameroon     295  500            1   5  2.666667                   144  182

                     Possession (%)
                 std           mean
Team
Argentina  38.774685      49.285714
Australia  17.682383      31.250000
Belgium    14.422205      49.000000
Brazil     10.691118      50.400000
Cameroon   19.857828      38.333333

In [21]:
fifa_df.head(100)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,48,Brazil,Cameroon,G,0,56,0,0,0,...,14,1,548,491,28,8,11,14,0,0
96,97,49,Netherlands,United States,A,3,35,3,0,3,...,10,0,403,331,15,5,4,8,0,3
97,98,49,United States,Netherlands,B,1,52,1,0,1,...,5,3,572,499,40,9,5,10,0,0
98,99,50,Argentina,Australia,C,2,53,2,0,1,...,8,4,711,635,6,1,1,15,0,3
99,100,50,Australia,Argentina,D,1,35,0,0,0,...,15,0,450,381,15,2,3,11,0,0

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

In [22]:
ipl = pd.read_csv("ipl.csv")
print(ipl.shape)
ipl.columns

(60104, 21)

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [23]:
# code here

#batting in 2nd inning=chasing acc to individual matches

Chasing_Matches=ipl[(ipl["inning"]==2)]
ipl_group=Chasing_Matches.groupby(["match_id","batsman"])
ipl_group["batsman_runs"].sum().sort_values(ascending=False).reset_index().iloc[0]["batsman"]

'PC Valthaty'

In [24]:
#chasing and have faced 100+ balls in 2nd inning

Chasing_no_wide_balls=ipl[(ipl["inning"]==2) & (ipl["wide_runs"]==0)]

In [34]:
batsman_balls=Chasing_no_wide_balls["batsman"].value_counts()


ipl_group=Chasing_no_wide_balls.groupby(["match_id","batsman"])
ipl_group.apply(lambda x:(x["batsman_runs"].sum()/x["batsman_runs"].count() if batsman_balls[x.name[1]]>100 else 0)*100).sort_values(ascending=False).head(2)

C:\Users\Nevid\AppData\Local\Temp\ipykernel_7396\1581678251.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ipl_group.apply(lambda x:(x["batsman_runs"].sum()/x["batsman_runs"].count() if batsman_balls[x.name[1]]>100 else 0)*100).sort_values(ascending=False).head(2)

match_id  batsman
49        A Mishra    400.0
170       A Mishra    325.0
dtype: float64

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [26]:
dismissed_ipl=ipl[~ipl["player_dismissed"].isnull()]

In [32]:
# code here
bobat=dismissed_ipl.groupby(['bowler',"batsman"])
bobat.agg({ "batsman_runs":["sum","count"]
    }).sort_values([("batsman_runs","count"),("batsman_runs","sum")],ascending=[False,True]).iloc[0].name

('DJ Bravo', 'SK Raina')

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [50]:
# code here
ipl["Batting_pair"]=ipl[["batsman","non_striker"]].apply(sorted,axis=1).apply(tuple)
ipl.shape

(60104, 22)

In [52]:
batting_pair=ipl.groupby("Batting_pair")
batting_pair["batsman_runs"].sum().sort_values(ascending=False)

Batting_pair
(AC Gilchrist, HH Gibbs)          866.0
(G Gambhir, V Sehwag)             866.0
(SR Tendulkar, ST Jayasuriya)     667.0
(DA Warner, S Dhawan)             617.0
(MS Dhoni, SK Raina)              543.0
                                  ...
(AM Nayar, DJ Thornely)             0.0
(A Mishra, DB Ravi Teja)            0.0
(A Choudhary, S Badree)             0.0
(SK Warne, SW Tait)                 0.0
(SN Thakur, Washington Sundar)      0.0
Name: batsman_runs, Length: 1449, dtype: float64

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [103]:
batting_pair.head(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder,Batting_pair
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,"(DA Warner, S Dhawan)"
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,"(DA Warner, S Dhawan)"
12,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,6,MC Henriques,S Dhawan,A Choudhary,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,"(MC Henriques, S Dhawan)"
13,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,A Choudhary,0.0,...,0.0,0.0,0.0,4.0,0.0,4.0,NaN,NaN,NaN,"(MC Henriques, S Dhawan)"
65,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,11,4,MC Henriques,Yuvraj Singh,STR Binny,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,NaN,NaN,NaN,"(MC Henriques, Yuvraj Singh)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60006,254,1,Pune Warriors,Mumbai Indians,17,2,R Sharma,SB Wagh,SL Malinga,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,NaN,NaN,NaN,"(R Sharma, SB Wagh)"
60009,254,1,Pune Warriors,Mumbai Indians,17,5,AC Thomas,R Sharma,SL Malinga,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,"(AC Thomas, R Sharma)"
60010,254,1,Pune Warriors,Mumbai Indians,17,6,AC Thomas,R Sharma,SL Malinga,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,"(AC Thomas, R Sharma)"
60013,254,2,Mumbai Indians,Pune Warriors,1,1,JEC Franklin,SR Tendulkar,AC Thomas,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,"(JEC Franklin, SR Tendulkar)"
60014,254,2,Mumbai Indians,Pune Warriors,1,2,JEC Franklin,SR Tendulkar,AC Thomas,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,"(JEC Franklin, SR Tendulkar)"

In [102]:
df1=batting_pair.agg(
    Runs=("batsman_runs", "sum"),
    Avg=("batsman_runs", "mean"),
).reset_index()
temp_df=df1["Batting_pair"]
df1["Batsman1"]=temp_df.apply(lambda x:x[0])
df1["Batsman2"]=temp_df.apply(lambda x:x[1])


# df1["Runs"]=df1["batsman_runs"]["sum"]
# df1["Avg"]=df1["batsman_runs"]["mean"]
# df1.drop("batsman_runs", axis=1,inplace=True)
df1

,Batting_pair,Runs,Avg,Batsman1,Batsman2
0,"(A Chopra, BJ Hodge)",24.0,0.510638,A Chopra,BJ Hodge
1,"(A Chopra, SC Ganguly)",71.0,1.092308,A Chopra,SC Ganguly
2,"(A Chopra, Salman Butt)",49.0,0.790323,A Chopra,Salman Butt
3,"(A Choudhary, S Aravind)",21.0,0.913043,A Choudhary,S Aravind
4,"(A Choudhary, S Badree)",0.0,0.000000,A Choudhary,S Badree
...,...,...,...,...,...
1444,"(V Shankar, Yuvraj Singh)",24.0,1.263158,V Shankar,Yuvraj Singh
1445,"(VVS Laxman, Y Venugopal Rao)",14.0,0.736842,VVS Laxman,Y Venugopal Rao
1446,"(WA Mota, Yuvraj Singh)",10.0,0.833333,WA Mota,Yuvraj Singh
1447,"(WD Parnell, Yuvraj Singh)",39.0,2.166667,WD Parnell,Yuvraj Singh
1448,"(WPUJC Vaas, Y Venugopal Rao)",41.0,1.576923,WPUJC Vaas,Y Venugopal Rao

In [ ]:
# code here

In [38]:
tf=pd.DataFrame({
    "b":["nevi","badal"],
    "ns":["badal","nevi"],
    "rn":[6,8]
})
tf

       b     ns  rn
0   nevi  badal   6
1  badal   nevi   8

       b     ns  rn  hell0
0   nevi  badal   6      1
1  badal   nevi   8      2